import { expect, test } from '@playwright/test'

test('owner configures business, stores and registers with safe deactivation', async ({ page }) => {
  test.setTimeout(90_000)
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.message))
  await page.goto('/')
  await page.getByLabel('Email address').fill('setup-browser@example.com')
  await page.getByLabel('Password', { exact: true }).fill('browser setup passphrase only')
  await page.getByLabel('Authenticator or backup code').fill('00000000000000000001')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('combobox', { name: 'Organization', exact: true }).selectOption({ label: 'Setup first business' })
  await expect(page.getByRole('button', { name: 'Configure business' })).toBeDisabled()
  await page.getByLabel('Password for setup').fill('browser setup passphrase only')
  await page.getByLabel('Authenticator or backup code').fill('00000000000000000002')
  await page.getByRole('button', { name: 'Unlock setup', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Configure business' })).toBeEnabled()
  await page.getByRole('button', { name: 'Configure business' }).click()
  const business = page.getByRole('region', { name: 'Business details', exact: true })
  await business.getByLabel('Contact email').fill('shop@example.com')
  await business.getByRole('combobox', { name: 'Currency', exact: true }).selectOption('NPR')
  await business.getByLabel('Receipt footer').fill('Thank you for shopping with us')
  await business.getByRole('button', { name: 'Save business settings' }).click()
  await expect(page.getByRole('button', { name: 'Edit business settings' })).toBeVisible()
  await page.getByRole('button', { name: 'Add store', exact: true }).click()
  const addStore = page.getByRole('region', { name: 'Add a store', exact: true })
  await addStore.getByLabel('Store code').fill('MAIN')
  await addStore.getByLabel('Store name').fill('Main branch')
  await addStore.getByLabel('Address').fill('Market Road, Kathmandu')
  await addStore.getByLabel('Opening hours').fill('Sunday–Friday, 9 am–7 pm')
  await addStore.getByRole('button', { name: 'Save store' }).click()
  const main = page.getByRole('article', { name: 'Store Main branch', exact: true })
  await expect(main).toBeVisible()
  await main.getByRole('button', { name: 'Add register' }).click()
  let registerForm = page.getByRole('region', { name: 'Add a register', exact: true })
  await registerForm.getByLabel('Register code').fill('POS1')
  await registerForm.getByLabel('Register name').fill('Front counter')
  await registerForm.getByRole('button', { name: 'Save register' }).click()
  await expect(main.getByText('Front counter', { exact: true })).toBeVisible()
  await main.getByRole('button', { name: 'Add register' }).click()
  registerForm = page.getByRole('region', { name: 'Add a register', exact: true })
  await registerForm.getByLabel('Register code').fill('POS1')
  await registerForm.getByLabel('Register name').fill('Duplicate counter')
  await registerForm.getByRole('button', { name: 'Save register' }).click()
  await expect(page.getByRole('alert')).toContainText('already exists')
  await page.getByRole('button', { name: 'Reload latest details' }).click()
  await main.getByRole('button', { name: 'Rename', exact: true }).click()
  const rename = page.getByRole('region', { name: 'Rename register', exact: true })
  await rename.getByLabel('Register name').fill('Main counter')
  await rename.getByRole('button', { name: 'Save register' }).click()
  await expect(main.getByText('Main counter', { exact: true })).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await main.getByRole('button', { name: 'Deactivate store', exact: true }).click()
  await expect(main.getByRole('button', { name: 'Add register' })).toBeDisabled()
  await expect(main.getByText('POS1 · Inactive', { exact: true })).toBeVisible()
  await main.getByRole('button', { name: 'Activate store', exact: true }).click()
  await expect(main.getByText('POS1 · Inactive', { exact: true })).toBeVisible()
  await main.getByRole('button', { name: 'Activate', exact: true }).click()
  await expect(main.getByText('POS1 · Active', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add store', exact: true }).click()
  await addStore.getByLabel('Store code').fill('SECOND')
  await addStore.getByLabel('Store name').fill('Second branch')
  await addStore.getByRole('button', { name: 'Save store' }).click()
  await expect(page.getByRole('article', { name: 'Store Second branch' })).toBeVisible()
  await expect(main).not.toBeVisible()
  await page.getByRole('combobox', { name: 'Store view', exact: true }).selectOption({ label: 'All stores' })
  await expect(main).toBeVisible()
  await page.getByRole('combobox', { name: 'Store view', exact: true }).selectOption({ label: 'Main branch' })
  await expect(page.getByRole('article', { name: 'Store Second branch' })).not.toBeVisible()
  await page.getByRole('combobox', { name: 'Organization', exact: true }).selectOption({ label: 'Setup second business' })
  await expect(page.getByText('Your first store starts here')).toBeVisible()
  await expect(main).not.toBeVisible()
  await page.getByRole('combobox', { name: 'Organization', exact: true }).selectOption({ label: 'Setup first business' })
  await expect(main).toBeVisible()
  await page.reload()
  await page.getByRole('combobox', { name: 'Organization', exact: true }).selectOption({ label: 'Setup first business' })
  await expect(main.getByText('Main counter', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 375, height: 812 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375)
  await page.screenshot({ path: 'test-results/store-setup-mobile.png', fullPage: true })
  expect(failures).toEqual([])
})
