import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, MapPin, Plus, RefreshCw, Search, Store as StoreIcon } from 'lucide-react'
import type { ReactNode } from 'react'
import type { Register, Setup, Store } from './StoreSetup'
import './store-directory.css'

type Props = {
  data: Setup; selectedId: string; select: (id: string) => void; busy: boolean;
  refreshing: boolean; refresh: () => void; openSettings?: () => void;
  addStore: () => void; editStore: (store: Store) => void;
  addRegister: (store: Store) => void; editRegister: (store: Store, register: Register) => void;
  status: (store: Store, register?: Register) => Promise<void>
}

function StoreStatus({ active }: { active: boolean }) { return <span className={`stores-status ${active ? 'is-active' : 'is-inactive'}`}>{active ? 'Active' : 'Inactive'}</span> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <div><dt>{label}</dt><dd>{children || <span className="stores-muted">Not provided</span>}</dd></div> }

export default function StoreDirectory(props: Props) {
  const { data, selectedId, select, busy, refreshing, refresh, openSettings, addStore, editStore, status } = props
  const [search, setSearch] = useState('')
  const [filter, setFilter] = useState('all')
  const [sort, setSort] = useState('name')
  const selected = data.stores.find(store => store.id === selectedId)
  const activeRegisters = data.stores.reduce((total, store) => total + (store.active ? store.registers.filter(register => register.active).length : 0), 0)
  const visible = data.stores.filter(store => (filter === 'all' || (filter === 'active') === store.active) && `${store.name} ${store.code} ${store.address} ${store.phone} ${store.contact_email}`.toLowerCase().includes(search.trim().toLowerCase())).sort((a, b) => sort === 'registers' ? b.registers.length - a.registers.length || a.name.localeCompare(b.name) : a.name.localeCompare(b.name))
  function open(id: string) { select(id); document.querySelector('.controller-main')?.scrollTo({ top: 0 }) }
  function back() { const id = selectedId; select(''); requestAnimationFrame(() => (document.getElementById(`store-row-${id}`) || document.querySelector<HTMLInputElement>('.stores-search input'))?.focus()) }
  if (selected) return <StoreDetail {...props} store={selected} back={back} />
  return <div className="stores-directory">
    <div className="stores-directory-heading"><p>Manage your locations and checkout registers.</p><div className="stores-heading-actions"><button className="secondary-button icon-button" disabled={busy || refreshing} onClick={refresh}><RefreshCw size={15} aria-hidden="true" />Refresh</button><button className="primary-button icon-button" disabled={busy || !data.organization.configured || data.stores.length >= data.organization.store_limit} onClick={addStore}><Plus size={16} aria-hidden="true" />Add store</button></div></div>
    <div className="stores-directory-summary"><span><strong>{data.stores.length}</strong> stores</span><span><strong>{data.stores.filter(store => store.active).length}</strong> active</span><span><strong>{activeRegisters}</strong> active registers</span><span><strong>{data.stores.length} / {data.organization.store_limit}</strong> store slots used</span></div>
    {data.stores.length >= data.organization.store_limit && <div className="stores-capacity-note"><p>Store allowance reached. Request more stores in Organization settings.</p>{openSettings && <button className="secondary-button" onClick={openSettings}>Open settings</button>}</div>}
    <section className="stores-table-panel" aria-label="Store directory">
      <div className="stores-table-toolbar"><label className="stores-search"><Search size={17} aria-hidden="true" /><span className="sr-only">Search stores</span><input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search stores, codes or locations" /></label><label><span className="sr-only">Store status</span><select aria-label="Store status" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label><span className="sr-only">Sort stores</span><select aria-label="Sort stores" value={sort} onChange={event => setSort(event.target.value)}><option value="name">Name A–Z</option><option value="registers">Most registers</option></select></label></div>
      {visible.length ? <div className="stores-table-scroll" role="region" aria-label="Stores table" tabIndex={0}><table className="stores-table"><caption className="sr-only">Store locations, status, registers and actions. Select a store to view its full details.</caption><thead><tr><th scope="col">Store</th><th scope="col">Status</th><th scope="col">Location & contact</th><th scope="col">Registers</th><th scope="col">Actions</th></tr></thead><tbody>{visible.map(store => <tr key={store.id} onClick={() => { if (!busy) open(store.id) }}><th scope="row"><button id={`store-row-${store.id}`} className="stores-name-button" disabled={busy} onClick={event => { event.stopPropagation(); open(store.id) }} aria-label={`View store ${store.name}`}><span className="stores-mark"><StoreIcon size={18} aria-hidden="true" /></span><span><strong>{store.name}</strong><small>{store.code}</small></span><ArrowRight size={15} aria-hidden="true" /></button></th><td><StoreStatus active={store.active} /></td><td><span className="stores-location">{store.address || 'Address not provided'}</span><small>{store.phone || store.contact_email || 'Contact not provided'}</small></td><td><strong className="stores-register-count">{store.registers.length}</strong><small>{store.active ? store.registers.filter(register => register.active).length : 0} active</small></td><td onClick={event => event.stopPropagation()}><div className="stores-row-actions"><button className="stores-text-button" disabled={busy} aria-label={`Edit store ${store.name}`} onClick={() => editStore(store)}>Edit</button><button className="stores-text-button" disabled={busy} aria-label={`${store.active ? 'Deactivate' : 'Activate'} store ${store.name}`} onClick={() => void status(store)}>{store.active ? 'Deactivate' : 'Activate'}</button></div></td></tr>)}</tbody></table></div> : <div className="stores-empty"><StoreIcon size={28} aria-hidden="true" /><h3>{data.stores.length ? 'No matching stores' : 'Add your first store'}</h3><p>{data.stores.length ? 'Try another search or status filter.' : 'Create a store for each business location, then add its checkout registers.'}</p>{data.stores.length > 0 && <button className="secondary-button" onClick={() => { setSearch(''); setFilter('all') }}>Clear filters</button>}</div>}
      <div className="stores-table-footer">{visible.length} of {data.stores.length} stores<span>Inactive stores still use a store slot.</span></div>
    </section>
  </div>
}

function StoreDetail({ store, back, busy, refreshing, refresh, editStore, addRegister, editRegister, status }: Props & { store: Store; back: () => void }) {
  const heading = useRef<HTMLHeadingElement>(null)
  useEffect(() => { heading.current?.focus({ preventScroll: true }) }, [store.id])
  const activeRegisters = store.active ? store.registers.filter(register => register.active).length : 0
  return <article className="stores-detail" aria-label={`Store ${store.name}`}>
    <button className="back-link icon-button stores-back" disabled={busy} onClick={back}><ArrowLeft size={16} aria-hidden="true" />All stores</button>
    <header className="stores-detail-heading"><span className="stores-mark"><StoreIcon size={24} aria-hidden="true" /></span><div><p className="eyebrow">{store.code}</p><h2 ref={heading} tabIndex={-1}>{store.name}</h2><p>{store.address || 'Address not provided'}</p></div><StoreStatus active={store.active} /><div className="stores-heading-actions"><button className="secondary-button icon-button" disabled={busy || refreshing} onClick={refresh} aria-label="Refresh store details"><RefreshCw size={15} aria-hidden="true" /></button><button className="secondary-button" disabled={busy} onClick={() => editStore(store)}>Edit store</button><button className="secondary-button" disabled={busy} onClick={() => void status(store)}>{store.active ? 'Deactivate store' : 'Activate store'}</button></div></header>
    <div className="stores-detail-grid"><section className="panel stores-profile"><div className="stores-section-heading"><MapPin size={17} aria-hidden="true" /><h3>Store details</h3></div><dl className="stores-fields"><Field label="Address">{store.address}</Field><Field label="Timezone">{store.timezone}</Field><Field label="Phone">{store.phone && <a href={`tel:${store.phone}`}>{store.phone}</a>}</Field><Field label="Contact email">{store.contact_email && <a href={`mailto:${store.contact_email}`}>{store.contact_email}</a>}</Field><Field label="Opening hours">{store.opening_hours}</Field><Field label="Registers">{store.registers.length} total · {activeRegisters} active</Field></dl></section><section className="panel stores-receipt"><div className="stores-section-heading"><h3>Receipt identity</h3></div><div className="stores-receipt-preview"><strong>{store.receipt_name || store.name}</strong><p>{store.address || 'Address not provided'}</p>{store.phone && <p>{store.phone}</p>}<div>{store.receipt_footer || <span className="stores-muted">No receipt footer added</span>}</div></div></section></div>
    <section className="stores-table-panel" aria-label="Store registers"><div className="stores-register-heading"><div><h3>Registers</h3><p>{activeRegisters} active · {store.registers.length} total</p></div><button className="primary-button icon-button" disabled={busy || !store.active} onClick={() => addRegister(store)}><Plus size={16} aria-hidden="true" />Add register</button></div>
      {!store.active && <p className="stores-inactive-notice">Activate this store before adding or activating registers.</p>}
      {store.registers.length ? <div className="stores-table-scroll" role="region" aria-label="Registers table" tabIndex={0}><table className="stores-table stores-register-table"><caption className="sr-only">Registers for {store.name}</caption><thead><tr><th scope="col">Register</th><th scope="col">Code</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody>{store.registers.map(register => <tr key={register.id}><th scope="row">{register.name}</th><td>{register.code}</td><td><StoreStatus active={store.active && register.active} /></td><td><div className="stores-row-actions"><button className="stores-text-button" disabled={busy || !store.active} aria-label={`Rename register ${register.name}`} onClick={() => editRegister(store, register)}>Rename</button><button className="stores-text-button" disabled={busy || (!store.active && !register.active)} aria-label={`${register.active ? 'Deactivate' : 'Activate'} register ${register.name}`} onClick={() => void status(store, register)}>{register.active ? 'Deactivate' : 'Activate'}</button></div></td></tr>)}</tbody></table></div> : <div className="stores-empty"><h3>No registers yet</h3><p>Add the first checkout counter for this store.</p></div>}
    </section>
  </article>
}
